DataFrame

A DataFrame is a 2-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns).
Think of it like an Excel sheet or SQL table.

In [3]:
import pandas as pd 
data={
    "name":["bill","tom","tim","dev","alex","vanessa","kate"],
    "score":[90,80,85,75,95,60,65],
    "sport":["wrestling","football","skiing","swimming","tennis","karete","surfing"],
    "sex":["m","m","m","m","m","f","f"]
}
df=pd.DataFrame(data)

In [5]:
df

      name  score      sport sex
0     bill     90  wrestling   m
1      tom     80   football   m
2      tim     85     skiing   m
3      dev     75   swimming   m
4     alex     95     tennis   m
5  vanessa     60     karete   f
6     kate     65    surfing   f

In [13]:
interested_col_df = df[['name','score','sport']]

In [17]:
interested_col_df

      name  score      sport
0     bill     90  wrestling
1      tom     80   football
2      tim     85     skiing
3      dev     75   swimming
4     alex     95     tennis
5  vanessa     60     karete
6     kate     65    surfing

In [7]:
df = pd.DataFrame(data,columns=['name','sport','score'])
print(df)

      name      sport  score
0     bill  wrestling     90
1      tom   football     80
2      tim     skiing     85
3      dev   swimming     75
4     alex     tennis     95
5  vanessa     karete     60
6     kate    surfing     65

In [9]:
df.head() #default 5 rows

   name      sport  score
0  bill  wrestling     90
1   tom   football     80
2   tim     skiing     85
3   dev   swimming     75
4  alex     tennis     95

In [11]:
df.tail(5) # Last 5 rows

      name     sport  score
2      tim    skiing     85
3      dev  swimming     75
4     alex    tennis     95
5  vanessa    karete     60
6     kate   surfing     65

In [19]:
df.sample(n=3)

   name      sport  score
0  bill  wrestling     90
2   tim     skiing     85
4  alex     tennis     95

In [21]:
import pandas as pd 
data={
    "name":["bill","tom","tim","dev","alex","vanessa","kate"],
    "score":[90,80,85,75,95,60,65],
    "sport":["wrestling","football","skiing","swimming","tennis","karete","surfing"],
    "sex":["m","m","m","m","m","f","f"]
}
df=pd.DataFrame(data)

In [23]:
df.describe()

           score
count   7.000000
mean   78.571429
std    12.817399
min    60.000000
25%    70.000000
50%    80.000000
75%    87.500000
max    95.000000

In [25]:
df.columns

Index(['name', 'score', 'sport', 'sex'], dtype='object')

Accessing and indexing data in dataframe

In [28]:
df

      name  score      sport sex
0     bill     90  wrestling   m
1      tom     80   football   m
2      tim     85     skiing   m
3      dev     75   swimming   m
4     alex     95     tennis   m
5  vanessa     60     karete   f
6     kate     65    surfing   f

In [30]:
#Accesing a single column
name_data_frame = df ['name']

##accessing multiple columns
print(df[['name','sport','score']])

      name      sport  score
0     bill  wrestling     90
1      tom   football     80
2      tim     skiing     85
3      dev   swimming     75
4     alex     tennis     95
5  vanessa     karete     60
6     kate    surfing     65

In [32]:
## Accessing a specific row by index
print(df.iloc[2]) #third row (index 2)

##accessing a range of rows using slicing
print(df.iloc[1:4])# rows with indices 1,2,3

name        tim
score        85
sport    skiing
sex           m
Name: 2, dtype: object
  name  score     sport sex
1  tom     80  football   m
2  tim     85    skiing   m
3  dev     75  swimming   m

In [36]:
## Accessing a specific row by index
print(df.iloc[2]) #third row (index 2)

##accessing a range of rows using slicing
print(df.loc[1:4,['name','score']])# rows with indices 1,2,3

name        tim
score        85
sport    skiing
sex           m
Name: 2, dtype: object
   name  score
1   tom     80
2   tim     85
3   dev     75
4  alex     95

indexing with .loc[] and .iloc[]

- .loc[]:label:based indexing.it works with labels(row/column names)
- .iloc[]:position -based indexing. it works with integer positions(row/colum indices)

In [39]:
df.set_index('name', inplace=True)

In [41]:
df

         score      sport sex
name
bill        90  wrestling   m
tom         80   football   m
tim         85     skiing   m
dev         75   swimming   m
alex        95     tennis   m
vanessa     60     karete   f
kate        65    surfing   f

In [43]:
df.reset_index(inplace=True)
df

      name  score      sport sex
0     bill     90  wrestling   m
1      tom     80   football   m
2      tim     85     skiing   m
3      dev     75   swimming   m
4     alex     95     tennis   m
5  vanessa     60     karete   f
6     kate     65    surfing   f

In [45]:
df.set_index('name', inplace=True)

In [47]:
df

         score      sport sex
name
bill        90  wrestling   m
tom         80   football   m
tim         85     skiing   m
dev         75   swimming   m
alex        95     tennis   m
vanessa     60     karete   f
kate        65    surfing   f

In [51]:
# Accessing row by label(name)
print(df.loc['bill']) # row with index 1

score           90
sport    wrestling
sex              m
Name: bill, dtype: object

In [53]:
# Accessing specific value using labels
print(df.loc['bill','score']) # score of the person at index 1

90

In [57]:
#accessing row by integer position
print(df.iloc[1]) # second row(index 1)

score          80
sport    football
sex             m
Name: tom, dtype: object

In [59]:
print(df.iloc[3])

score          75
sport    swimming
sex             m
Name: dev, dtype: object

In [61]:
print(df.iloc[0])

score           90
sport    wrestling
sex              m
Name: bill, dtype: object

#accessing specific value using integer positions
print(df.iloc[1,2])#element  at row 1, column 1

In [65]:
print(df.iloc[1,[0,2]]) # element  at row 1, column 0 and 2

score    80
sex       m
Name: tom, dtype: object

slicing

- with .loc[]: both the start and stop are include.
- with .iloc[]: the stop is excluded.

In [68]:
df

         score      sport sex
name
bill        90  wrestling   m
tom         80   football   m
tim         85     skiing   m
dev         75   swimming   m
alex        95     tennis   m
vanessa     60     karete   f
kate        65    surfing   f

In [74]:
#using .loc for slicing (inclusive of end )
print(df.loc['bill':'tim','score':'sex'])

      score      sport sex
name
bill     90  wrestling   m
tom      80   football   m
tim      85     skiing   m

In [76]:
#using .loc for slicing (inclusive of end )
print(df.loc['bill':'tim','score':'sport'])

      score      sport
name
bill     90  wrestling
tom      80   football
tim      85     skiing

In [78]:
#using .iloc for slicing(exclusive of end)
print(df.iloc[1:3,0:2])

      score     sport
name
tom      80  football
tim      85    skiing

Filtering Data (boolean indexing)

In [81]:
# filtering based on a condition(e.g, score>80)
df[df['sex']=='m']

      score      sport sex
name
bill     90  wrestling   m
tom      80   football   m
tim      85     skiing   m
dev      75   swimming   m
alex     95     tennis   m

In [83]:
# filtering based on multiple conditions
print(df[(df['score']>80) & (df['sex']=='m')])

      score      sport sex
name
bill     90  wrestling   m
tim      85     skiing   m
alex     95     tennis   m

sorting data

In [86]:
#sorting by score
print(df.sort_values('score', ascending=False))

         score      sport sex
name
alex        95     tennis   m
bill        90  wrestling   m
tim         85     skiing   m
tom         80   football   m
dev         75   swimming   m
kate        65    surfing   f
vanessa     60     karete   f

In [90]:
print(df.sort_values(by=['sex','score'], ascending=[True,False]))

         score      sport sex
name
kate        65    surfing   f
vanessa     60     karete   f
alex        95     tennis   m
bill        90  wrestling   m
tim         85     skiing   m
tom         80   football   m
dev         75   swimming   m

importing and exporting data

with read table for general delimated file

In [107]:
df = pd.read_table(r"C:\Users\DELL\Desktop\datasets\datasets\data.txt")
df

  name  score sex
0  Tim     80   M
1  Tom     85   M
2  Kim     70   F
3  Sam     90   M
4  Efe     75   M

In [ ]:
df2=pd.read_csv()