In [5]:
import pandas as pd 
import numpy as np

In [7]:
from numpy import nan as NA

In [9]:
df = pd.DataFrame([[1,2,3],[4,None,5],
                 [NA,NA,NA]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [11]:
df.fillna(df.mean(axis=1))

     0    1    2
0  1.0  2.0  3.0
1  4.0  4.5  5.0
2  2.0  4.5  NaN

combinging and merging datasets in pandas

In [14]:
import pandas as pd

joining Dataframe

In [23]:
d1=pd.DataFrame(
    {"key":['a','b','c','d','e','f'],
    "num1":range(6)}
)

d2=pd.DataFrame(
    {"key":['b','c','e','f'],
    "num2":range(4)}
)

In [25]:
print(d1)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   d     3
4   e     4
5   f     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3

In [27]:
pd.merge(d1,d2)

  key  num1  num2
0   b     1     0
1   c     2     1
2   e     4     2
3   f     5     3

In [29]:
pd.merge(d1,d2,on='key')

  key  num1  num2
0   b     1     0
1   c     2     1
2   e     4     2
3   f     5     3

dataset having different key names

In [52]:
d3=pd.DataFrame(
    {"key1":['a','b','c','d','e','f'],
    "num1":range(6)}
)

d4=pd.DataFrame(
    {"key2":['b','c','e','f'],
    "num2":range(4)}
)

In [54]:
print(d3)
print(d4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4
5    f     5
  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3

In [56]:
pd.merge(
    d3,d4,left_on='key1',right_on="key2")

  key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    e     4    e     2
3    f     5    f     3

outer join

all rows from both datframes,with NAN where no match is found

In [60]:
print(d1)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   d     3
4   e     4
5   f     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3

In [62]:
pd.merge(d1,d2,how='outer')

  key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   d     3   NaN
4   e     4   2.0
5   f     5   3.0

left join

In [65]:
pd.merge(d1,d2,how='left')

  key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   d     3   NaN
4   e     4   2.0
5   f     5   3.0

right join

In [68]:
pd.merge(d1,d2,how='right')

  key  num1  num2
0   b     1     0
1   c     2     1
2   e     4     2
3   f     5     3

merging on index

In [79]:
df1=pd.DataFrame(
    {"letter":['a','a','b','b','a','c'],
     'num':range(6)
    
})
df2=pd.DataFrame(
    {"value":[3,5,7]},
     index=['a','b','e']
    
)

In [81]:
print(df1)
print(df2)

  letter  num
0      a    0
1      a    1
2      b    2
3      b    3
4      a    4
5      c    5
   value
a      3
b      5
e      7

In [83]:
pd.merge(df1,df2,
        left_on='letter',
        right_index=True)

  letter  num  value
0      a    0      3
1      a    1      3
2      b    2      5
3      b    3      5
4      a    4      3

In [86]:
data1=pd.DataFrame(
    [[1,2],[3,4],[5,6]],
    index=['a','c','d'],
    columns=['tom','tim']
)

data2=pd.DataFrame(
    [[7,8],[9,10],[11,12],[13,14]],
    index=['a','b','e','f'],
    columns=['sam','kim']
)

In [88]:
print(data1)
print(data2)

   tom  tim
a    1    2
c    3    4
d    5    6
   sam  kim
a    7    8
b    9   10
e   11   12
f   13   14

In [98]:
pd.merge(data1,data2,
        right_index=True,
        left_index=True,
        how='outer' )

   tom  tim   sam   kim
a  1.0  2.0   7.0   8.0
b  NaN  NaN   9.0  10.0
c  3.0  4.0   NaN   NaN
d  5.0  6.0   NaN   NaN
e  NaN  NaN  11.0  12.0
f  NaN  NaN  13.0  14.0

In [100]:
data2.join(data1)

   sam  kim  tom  tim
a    7    8  1.0  2.0
b    9   10  NaN  NaN
e   11   12  NaN  NaN
f   13   14  NaN  NaN

In [102]:
data1.join(data2,how='outer')

   tom  tim   sam   kim
a  1.0  2.0   7.0   8.0
b  NaN  NaN   9.0  10.0
c  3.0  4.0   NaN   NaN
d  5.0  6.0   NaN   NaN
e  NaN  NaN  11.0  12.0
f  NaN  NaN  13.0  14.0